name: geospatial_data_science
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6    # Python version 3.6
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - h5py          # Wrapper for HDF5
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - notebook      # Notebook interface
    - numpy         # N-d array and numerics
    - geopandas     # 
    - pandas        # Labeled array library
    - pyresample    # Geographic resampling tools
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Macine learning library
    - scikit-image  # Image processing routines
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - xarray        # N-d labeled array library
    - nb_conda
    - holoviews
    - geoviews
    - gsw
